global_nodes:
    address_node:
        address:
            -   address_belong: address

    office_node:
        office:
            -   office_belong:
                    office_type:
                        -   office_belong: office_type
paths:
    性别:
        person:
            -   gender_is: gender
    民族:
        person:
            -   ethnicity_is: ethnicity
    官职:
        person:
            -   do:
                    post:
                        -   first_year: year
                        -   last_year: year
                        -   office_is: office_node
                        -   post_is: post_type
                        -   where: address_node
    写作:
        person:
            -   text_is: text
    关系:
        person:
            -   do:
                    associate_event:
                        -   associate_belong: association
                        -   associate_is: person
                        -   first_year: year
                        -   occasion_is: occasion
                        -   topic_is: scholar
                        -   where: address_node
    定位:
        person:
            -   house_hold_is: house_hold
    社会区分:
        person:
            -   status_is: status
    地点事件: # todo 这里是不对的(学长的注释)
        person:
            -   address_associate_is:
                    address_type:
                        -   where: address_node
    入仕:
        person:
            -   do:
                    entry_event:
                        -   entry_is:
                                entry:
                                    -   entry_is:
                                            entry_type:
                                                -   entry_belong: entry_type
                        -   first_year: year
                        -   note_is: note


